### ISSUE TITLE
Cut v0.3.0 release?

### ISSUE THREAD

**Issue by jdolitsky** [sigstore/policy-controller#120]
Number of things since v0.2.0, including #112 

Perhaps we upgrade Go mods and cut another release? cc @cpanato

**Comment by jdolitsky** [comment]
Relevant: https://github.com/sigstore/policy-controller/issues/71

**Comment by hectorj2f** [comment]
Based on my own criteria, i am mot sure, there are enough reason for a new minor version. It sounds more like a patch version in my opinion.

**Comment by cpanato** [comment]
agree with @hectorj2f most are bug fixes updates

if all agree i will prepare the 0.2.1 release

**Comment by jdolitsky** [comment]
SGTM

**Comment by cpanato** [comment]
v0.2.1 is out https://github.com/sigstore/policy-controller/releases/tag/v0.2.1

**Comment by hectorj2f** [comment]
Thanks everyone
