### ISSUE TITLE
Reduce verbosity option in policy-tester

### ISSUE THREAD

**Issue by brajbou** [sigstore/policy-controller#1219]
Currently, when running policy-tester, the logging is very verbose and hard to read.  It would be great to have an option to reduce logging to just a pass/fail output or not report the blob of an attestation (which is super long).  

The reason for the this ask is we would like to use the policy-tester in a cronjob and/or gitlab pipeline to report policy failures and currently the job log is so long it can only be opened in "raw mode".

Example:
./policy-tester --quiet or -q

An example output:
 - remove DEBUG blah from each line
 -  remove image name in the validated signature output
 - remove Converted signature blob completely

2024-01-26T08:50:25.105-0500  Checking Authority: aws-key
2024-01-26T08:50:27.009-0500  validated signature  for authority aws-key got 1 signatures

**Comment by hectorj2f** [comment]
@brajbou You can configure the verbosity level now: https://github.com/sigstore/policy-controller/pull/1414
