### ISSUE TITLE
RFC: Incorporate ctlog information into `PolicySignature`

### ISSUE THREAD

**Issue by mattmoor** [sigstore/policy-controller#124]
**Description**

When we are directed to perform `ctlog` verification with something like:
```yaml
    ctlog:
      url: http://rekor.rekor-system.svc
```

Perhaps we should incorporate some of the verified metadata into `PolicySignature`: https://github.com/sigstore/policy-controller/blob/abc02de7b9ced66b888306c3d640d1be2a649a5e/pkg/webhook/validator_result.go#L54-L57

I don't have any particular thoughts on specifically *what* to include here, but as a strawperson I'll suggest perhaps the cosign `Bundle` type?

cc @hectorj2f @vaikas @jdolitsky

**Comment by hectorj2f** [comment]
I'd say we need some real examples here. But i agree with the location in the api type to define those checks.

**Comment by hectorj2f** [comment]
Closing this issue! This has been done!
