### ISSUE TITLE
Not all the tests that should be required are required for submission

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#148]
**Description**
Need to vet and update this with the correct branch protections:
https://github.com/sigstore/community/blob/main/github-sync/github-data/repositories.yaml

Currently only these are 'required':
```
        statusChecks:
          - Run unit tests (ubuntu-latest)
          - lint
          - Verify codegen
          - check gofmt
          - license boilerplate check
          - Check Whitespace
          - DCO
          - check goimports

```

But that's not enough, need to add the proper e2e tests. This is especially troublesome with the 'enable automerge' which could cause accidental merges even if some of the tests are failing.

**Version**

**Comment by cpanato** [comment]
I will update those

Will post a list of checks that we want to make required and then when agreed will update

**Comment by vaikas** [comment]
Thank you @cpanato 

How do you figure out the name here?
https://github.com/sigstore/scaffolding/runs/7802190944?check_suite_focus=true

Or here:
https://github.com/sigstore/scaffolding/actions/runs/2845301906

I was going to do it, but I couldn't figure it out immediately how these names work, so filed the issue before I forget :)
