### ISSUE TITLE
No release yet for already merged AKS auth fix

### ISSUE THREAD

**Issue by dp-rp** [sigstore/policy-controller#1700]
**Description**

AKS authentication fixed in a PR but no release has been provided with the fix yet.

**issue:** https://github.com/sigstore/policy-controller/issues/1391

**merged fix:** https://github.com/sigstore/policy-controller/pull/1424

**last release:** https://github.com/sigstore/policy-controller/releases

**Version**

0.9.0

**Comment by avo-sepp** [comment]
+1 we need a new release even if just for dependency updates and cyber security patches that dependabot has been applying.

**Comment by hectorj2f** [comment]
I'll cut one release today.

**Comment by hectorj2f** [comment]
Done here: https://github.com/sigstore/policy-controller/releases/tag/v0.11.0

**Comment by avo-sepp** [comment]
Hi @hectorj2f, I notice the Helm chart isn't getting updated. It shows it's still installing 0.8

See here: https://github.com/sigstore/helm-charts/tree/main/charts/policy-controller
