### ISSUE TITLE
Support non-default signature digest algorithms

### ISSUE THREAD

**Issue by joshrwolf** [sigstore/policy-controller#234]
**Description**

Plumb through `--signature-digest-algorithm` support to the CIP's spec to allow specifying non-sha256 signature digest algorithms.

This would be analogous to the `cosign` workflow of:

```bash
cosign verify --key $key --signature-digest-algorithm sha512 $image
```

**Comment by hectorj2f** [comment]
Perhaps it could better fit as part of the CIP data model `authority.key.hashAlgorithm`  in https://github.com/sigstore/policy-controller/blob/main/pkg/apis/policy/v1beta1/clusterimagepolicy_types.go#L118

**Comment by vaikas** [comment]
Yeah, I think it should definitely be plumbed through the CIP spec 👍

**Comment by hectorj2f** [comment]
I am working on a branch to add support for this new field. I'll open PR soonish.

**Comment by hectorj2f** [comment]
It has been added as part of in https://github.com/sigstore/policy-controller/pull/237
