### ISSUE TITLE
Parallelize validation checks over containers

### ISSUE THREAD

**Issue by nsmith5** [sigstore/policy-controller#272]
**Description**

Policy validation [currently checks each container one at a time](https://github.com/sigstore/policy-controller/blob/4963d61971e06c2543019cc3737ee9dfdc4c5cea/pkg/webhook/validator.go#L164). These checks can involve a lot of blocking IO requesting signatures from repositories and fetching verification keys and such so with a pod with several containers, the latency on validation can grow to be quite high. Would be nice to parallelize these checks over containers similar to the [pattern already used to parallelize the checks over policies](https://github.com/sigstore/policy-controller/blob/4963d61971e06c2543019cc3737ee9dfdc4c5cea/pkg/webhook/validator.go#L301-L312)

**Comment by vaikas** [comment]
Woot woot! Thank you!

**Comment by hectorj2f** [comment]
@nsmith5 Yes, good remark. We need to do that.
