### ISSUE TITLE
Allow creating a ClusterImagePolicy without authorities

### ISSUE THREAD

**Issue by wojciechka** [sigstore/policy-controller#275]
As part of implementing `policy-controller` in an environment, we want a CD system to manage `ClusterImagePolicy` so GitOps approach can be applied for managing the `ClusterImagePolicy` objects.

Another entity (CronJob or perhaps a controller/operator) will update `spec.authorities` part for objects with specific label/annotation to replace `spec.authorities` with currently allowed public keys from our KMS system.

This is currently not possible as no `spec.authorities` is not possible. Specifying any values may cause CD to try to overwrite `spec.authorities` (and temporarily cause issues) whenever any other part of `ClusterImagePolicy` changes.

The error is:

```
The ClusterImagePolicy "example" is invalid: spec.authorities: Invalid value: "null": spec.authorities in body must be of type array: "null"
```

If GitOps and CD does not have a field and it is configured to ignore a difference, then the case is simpler as anything applied by CD does not modify said field.

It is possible to set up a default `authorities: [{"static": {"action": "fail"}}]`, but that may cause some CD tools to not work properly and the right way would be not set `spec.authorities`.

This could be done as a flag or setting for the appropriate webhook process or perhaps would require a specific field, label or annotation to be set.

**Comment by hectorj2f** [comment]
Yes, you cannot create policies without specifying which authorities to enforce. I am trying to understand why that cronjob does not create the ClusterImagePolicy whenever it knows which authorities to enforce.

**Comment by wojciechka** [comment]
> Yes, you cannot create policies without specifying which authorities to enforce. I am trying to understand why that cronjob does not create the ClusterImagePolicy whenever it knows which authorities to enforce.

I should have explained it in more details.

As for why - it is a common pattern, where CD is managing most fields, but some can be updated by other parts of Kubernetes. This way our tooling is aware of the CRDs and is applying changes to it, but we do not want our CD to be aware of public keys, which are rotated on a regular basis.

Even `policy-controller` uses a similar pattern. When setting up a deployment of it via CD, the CD was made to ignore the `caBundle` and some other fields in the webhook deployments manage for themselves. CD is managing most things and ensures the objects are there, but `caBundle` is updated by the `policy-controller`. The Kubernetes secrets for webhook credentials are also working this way. In those cases, CD is configured to ignore those fields and not populate them at all, having other tools populate them.

It's also common to use `cert-manager` this way - creating empty secrets or not creating them, having `cert-manager` update the secrets (and webhook configuration if that's a webhook).

As for why the CronJob would not be managing the objects - the current implementation is doing exactly that - rendering objects and calling `kubectl apply -f -`.

First drawback of this approach is any change to ClusterImagePolicy (i.e. change in image patterns) needs to wait for another run of the CronJob, which is suboptimal. Having CD update the image patterns as soon as change is merged is more natural in a GitOps environment.

Another drawback is that it's hard to manage said objects, especially if deploying it to multiple clusters - any rename or removal of a ClusterImagePolicy stops being a simple `kubectl apply` and we'd need to delete old policies (manually or via the CronJob). CD managing the object would do that for us.

Also, I am not saying this should be the default, as this could be confusing for less experienced users, I am just asking if this could be made configurable.

**Comment by vaikas** [comment]
Just to double-check, you just want to be able to create one without any authorities. If any authority is given, we'll still be validating it as per existing rules.

**Comment by hectorj2f** [comment]
@wojciechka Thanks for the detailed explanation 👏🏻 . It is clear now.

@vaikas Perhaps we could add a new tuple to the configuration configmap (you recently added it ) allowing CIPs without any authority. wdyt ?

**Comment by wojciechka** [comment]
> Just to double-check, you just want to be able to create one without any authorities. If any authority is given, we'll still be validating it as per existing rules.

Correct, that's what I want - be able to create one without `spec.authorities`, but continue to have validation when creating with or updating `spec.authorities`.

Thank you for your appreciation of this.

**Comment by vaikas** [comment]
Yeah, I think this is probably something that we may want to be able to control from the configmap?

**Comment by hectorj2f** [comment]
>  Yeah, I think this is probably something that we may want to be able to control from the configmap?

Sounds good to me.

**Comment by hectorj2f** [comment]
@wojciechka I created this PR to add this configurable behavior https://github.com/sigstore/policy-controller/pull/292

**Comment by hectorj2f** [comment]
Closing this issue! It is now supported as a configurable property.

**Comment by wojciechka** [comment]
@hectorj2f what is the best way to test this or experiment with this?

I deployed helm chart version 0.2.5 (policy-controller 0.3.0) and then ran:

```
kubectl apply -f- <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-policy-controller
  namespace: policy-controller
data:
  no-match-policy: 'deny'
  fail-on-empty-authorities: 'false'
EOF

kubectl patch deployment policy-controller-policy-webhook --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"gcr.io/projectsigstore/policy-controller/ci/policy-controller:fdb80f3665c02f0574b845941277bedb12b2447a"}]'
kubectl patch deployment policy-controller-webhook --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"gcr.io/projectsigstore/policy-controller/ci/policy-controller:fdb80f3665c02f0574b845941277bedb12b2447a"}]'
```

This updates the image to one built by CI from fdb80f3665c02f0574b845941277bedb12b2447a, which is the merge of #292 to master. After waiting for pods to restart, I am now getting this:

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "defaulting.clusterimagepolicy.sigstore.dev": failed to call webhook: Post "https://policy-webhook.policy-controller.svc:443/defaulting?timeout=10s": x509: certificate is valid for webhook, webhook.policy-controller, webhook.policy-controller.svc, webhook.policy-controller.svc.cluster.local, not policy-webhook.policy-controller.svc
```

I also tried doing the same but using commit `9ed1f43631a04c17c3f6e65982ba7c9dca3fff99` (which is the commit as release 0.3.0) and it is having same issues.

When I don't patch the image but do `kubectl rollout restart deployment/policy-controller-policy-webhook && kubectl rollout restart deployment/policy-controller-webhook` (which also restarts the deployments, but using same image as before), I am not seeing any issues and things continue to work fine.

So, I suspect I either can't use the CI image or need a different image to test it.

**Comment by hectorj2f** [comment]
@wojciechka We haven't created any new release since then, so you need to use our main branch for now `KO_PREFIX=<your_registry_project> make ko-apply` otherwise you can run `KO_PREFIX=<your_registry_project> make ko` and then simply `kubectl create -f policy-controller-dirty-tag.yaml`
