### ISSUE TITLE
Multiple authorities are treated as AND instead of OR

### ISSUE THREAD

**Issue by tcnghia** [sigstore/policy-controller#28]
**Description**

When specifying both `key` and `keyless` section in the ClusterImagePolicies, the webhook enforces both of them instead of one of them.

**Version**

**Comment by vaikas** [comment]
I think that could be a work around, but the spec says that multiple authorities should be `OR` together, so I do think this is a bug.

**Comment by dlorenc** [comment]
I'd lean toward OR. Key rotation scenarios (one of these two) seems to be more common than requiring multiple keys.

**Comment by vaikas** [comment]
Yeah, and well, that is what the Spec that we put together says. I just screwed up somewhere along the way, I'm fixing :)
