### ISSUE TITLE
Policy-controller should have a flexibility to work in air-gapped environments without TUF

### ISSUE THREAD

**Issue by rnachire** [sigstore/policy-controller#354]
**Policy-controller should have a flexibility to work in air-gapped environments without TUF**

Starting with v0.3.0 TUF integration has been started by default which makes a call to google store to fetch the root.json. Most of the customer environments we will not be able to whitelist these URLs for security concerns. 

Even when we provide tuf-root as mentioned in the [document](https://docs.sigstore.dev/policy-controller/installation) and mounting that to /var/run/tuf/root.json also didn't work. Could you provide an example from which release which is supported or how to verify that feature in k8s ? (one example k8s manifest would help). we have **kubectl create secret generic tuf-root --from-file=root=root.json -n test** in our usecase with mountpath specified.

Another followup question, If we go with static root.json embedded in code do we need to create the secret again in newer releases since we have seen https://github.com/sigstore/policy-controller/pull/353/ taken. Little more documentaiton about TUF will help in this.

We would like to have TUF integration as optional since keyless verification is also shouldn't be a default paradigm for all the usecases. For this, could you make the flexibility by allowing keyless vs static verification with KMS or other keys ? 

Please let us know, if you need more details. Really appreciate the efforts put in.

**Comment by dlorenc** [comment]
We should definitely support this scenario!

**Comment by hectorj2f** [comment]
@rnachire If we provide an internal TUF server setting a value for  `--tuf-mirror`, it'll work in an airgap environment. 
The main issue comes from the tuf initialization if we didn't set any TUF mirror. It relies on `https://sigstore-tuf-root.storage.googleapis.com/`. Anyway we are looking how to solve this scenario.

**Comment by wojciechka** [comment]
I'd like to request something similar - ability to disable TUF. The setup I am working on only has a set of public keys I provide (in our case we're signing all images we want to validate, using external signatures and signing it ourselves).

We're seeing an error initializing TUF for a few days. The environment has access to external URLs, but for some reason policy-controller 0.3.0 is rejecting the latest root.json in sigstore TUF:

```
{"level":"info","ts":1667204670.2733,"logger":"fallback","caller":"webhook/main.go:89","msg":"Initializing TUF root from  => https://sigstore-tuf-root.storage.googleapis.com"}
{"level":"panic","ts":1667204670.5000272,"logger":"fallback","caller":"webhook/main.go:91","msg":"Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key\nremote status:{\n\t\"mirror\": \"https://sigstore-tuf-root.storage.googleapis.com\",\n\t\"metadata\": {\n\t\t\"root.json\": {\n\t\t\t\"version\": 5,\n\t\t\t\"len\": 6388,\n\t\t\t\"expiration\": \"18 Apr 23 18:13 UTC\",\n\t\t\t\"error\": \"\"\n\t\t},\n\t\t\"snapshot.json\": {\n\t\t\t\"version\": 53,\n\t\t\t\"len\": 1973,\n\t\t\t\"expiration\": \"10 Nov 22 21:10 UTC\",\n\t\t\t\"error\": \"\"\n\t\t},\n\t\t\"targets.json\": {\n\t\t\t\"version\": 5,\n\t\t\t\"len\": 4188,\n\t\t\t\"expiration\": \"18 Apr 23 18:13 UTC\",\n\t\t\t\"error\": \"\"\n\t\t},\n\t\t\"timestamp.json\": {\n\t\t\t\"version\": 53,\n\t\t\t\"len\": 719,\n\t\t\t\"expiration\": \"03 Nov 22 21:10 UTC\",\n\t\t\t\"error\": \"\"\n\t\t}\n\t}\n}","stacktrace":"main.main\n\tgithub.com/sigstore/policy-controller/cmd/webhook/main.go:91\nruntime.main\n\truntime/proc.go:250"}
panic: Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key
remote status:{
	"mirror": "https://sigstore-tuf-root.storage.googleapis.com",
	"metadata": {
		"root.json": {
			"version": 5,
			"len": 6388,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"snapshot.json": {
			"version": 53,
			"len": 1973,
			"expiration": "10 Nov 22 21:10 UTC",
			"error": ""
		},
		"targets.json": {
			"version": 5,
			"len": 4188,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"timestamp.json": {
			"version": 53,
			"len": 719,
			"expiration": "03 Nov 22 21:10 UTC",
			"error": ""
		}
	}
}

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x1704dfa?, {0x0?, 0x0?, 0xc0002ca3c0?})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000f0f70, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc00040f0f0, 0x4, {0x2609657?, 0x0?}, {0xc00078fe60?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.23.0/sugar.go:287 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	go.uber.org/zap@v1.23.0/sugar.go:181
main.main()
	github.com/sigstore/policy-controller/cmd/webhook/main.go:91 +0x577
```

This is causing `policy-controller` to crash loop.

As we're not using TUF, it would be best there is a way to disable it - either via configuration or environment variable / command line flag if this step is happening before policy-controller's configuration gets initialized.

It would also be interesting to initialize TUF on first use or after `ClusterImagePolicy` that uses keyless authentication exists, but I suspect that would be much more complex to implement.

**Comment by wojciechka** [comment]
I can confirm that with `tuf.Initialize` removed from `cmd/webhook/main.go` and having `key`-based authorities things work as expected in my specific case.

**Comment by hectorj2f** [comment]
Thanks @wojciechka. Yeah, we might also combine it with some additional validations. We'll ping you when we open a PR with the suggested solution.

**Comment by vaikas** [comment]
Yeah, we should add a configuration option for disabling this. Flag is probably better. This is kind of in the middle between supporting only the public root as well as supporting multiples (including zero).

I started to implement this but been distracted with other things. I think in the short term we should just provide a flag that disables TUF alltogether. I can put this together in just a little bit, and we can then cut a release.
