### ISSUE TITLE
Multiple `source:` likely won't work as intended

### ISSUE THREAD

**Issue by mattmoor** [sigstore/policy-controller#360]
**Description**

I haven't explicitly tried this, but I'm fairly confident that this is a problem looking at the code.  Currently `source:` takes a list, but when we're unmarshalling things from our "compiled" form we call `WithTargetRepository` and I think the last one wins:

https://github.com/sigstore/policy-controller/blob/970ac4a04700727fe984376d878fbec1d0bcdcb5/pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go#L182

There's a related problem where we just sort of YOLO our way through the credentials and last-one wins here:

https://github.com/sigstore/policy-controller/blob/970ac4a04700727fe984376d878fbec1d0bcdcb5/pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go#L196-L197

I thought maybe we might be restricting the `source:` to a singleton for now, but that doesn't appear to be the case (and I was just talking to @dlorenc about how useful this being a list could be!):
https://github.com/sigstore/policy-controller/blob/970ac4a04700727fe984376d878fbec1d0bcdcb5/pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go#L142-L144

cc @hectorj2f @vaikas 

**Version**

HEAD, v0.4.1

**Comment by vaikas** [comment]
I'm going to restrict the validation to be a singleton entry in the list until we actually support it properly. It's a bigger change and I reckon that having it in a bad state is no good.
@mattmoor @hectorj2f
