### ISSUE TITLE
Cosigned Helm Chart - tls: no certificates configured

### ISSUE THREAD

**Issue by quadrinho** [sigstore/policy-controller#369]
**Description**

I have tried to deploy the last version of the cosigned chart but in the webhook and policy-webhook i received this errors:

{"level":"warn","ts":"2022-11-09T11:00:37.588Z","logger":"clusterimagepolicy","caller":"webhook/webhook.go:154","msg":"server key missing"}
2022/11/09 11:00:37 http: TLS handshake error from 10.199.120.107:43092: tls: no certificates configured

I installed the chart using this command:

helm upgrade -i cosigned . --devel -n default --set cosign.secretKeyRef.name=mysecret

In the "mysecret" kubernetes secret is present the public key cosign.pub that i retrieve from AWS KMS after creating on it the key:

CREATION OF THE KEY ON KMS:

aws kms create-key --key-usage SIGN_VERIFY --customer-master-key-spec RSA_4096 --description "KMS key for signing images"

RETRIEVE THE PUBLIC KEY:

aws kms get-public-key --key-id $KMS_ALIAS_ARN --query 'PublicKey' --output text | openssl enc -base64 -A -d -in /dev/stdin | openssl rsa -pubin -inform DER -outform PEM -in /dev/stdin -out cosign.pub

So i don't underst the above bold error.

**Version**
App Version 1.8.0
Chart Version 0.1.23

**Comment by hectorj2f** [comment]
@quadrinho You need to manually delete the leases `kubectl delete leases -n cosign-system` when you face this issue `server key missing`. They are automatically deleted but it takes some time until that happens. We cannot automatize this cleanup.

**Comment by hectorj2f** [comment]
you can find more info here https://github.com/sigstore/policy-controller/issues/41

**Comment by quadrinho** [comment]
Hello @hectorj2f,

Can you help me? Any ideas?

**Comment by hectorj2f** [comment]
@quadrinho the namespace label is incorrect `cosigned.sigstore.vdf/include="true`. Please check our README to find the right label.

**Comment by hectorj2f** [comment]
Use policy.sigstore.dev/include=true

**Comment by hectorj2f** [comment]
@quadrinho I am closing this issue. The problem was related to the label you used. Feel free to re-open it if you're still experiencing any issue.
