### ISSUE TITLE
Drop service account lookups when `signaturePullSecrets` are specified

### ISSUE THREAD

**Issue by mattmoor** [sigstore/policy-controller#382]
**Description**

Currently in `k8schain` it is ~impossible to avoid looking up pull secrets attached to a service account, however, I am plumbing through that option in: https://github.com/google/go-containerregistry/pull/1490

I believe that when `signaturePullSecrets` are explicitly specified that we should pass this new constant for `ServiceAccountName` here:
https://github.com/sigstore/policy-controller/blob/87267f39c925c0922c89e042980df43ef0bbe91e/pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go#L203-L206

... this request creates unnecessary load on the API server.

**Comment by hectorj2f** [comment]
@mattmoor 100% agree, we should avoid doing that call!
