### ISSUE TITLE
Allow policies to access image config(s) and resource spec

### ISSUE THREAD

**Issue by mattmoor** [sigstore/policy-controller#385]
**Description**

_This is capturing a convo @dlorenc and I were having for more discussion._

Two useful pieces of information for policy evaluation, which are readily available to the webhook, but the policy language does not currently have access to are:
1. The image's ["config file"](https://github.com/google/go-containerregistry/blob/781782aa2757f8eb6d3b7b7a32b25a799b64bc60/pkg/v1/config.go#L23)
2. The resource's `spec`

To not bury the lede...  Personally, I think the most straightforward option would be to simply include these two pieces of information as part of `PolicyResult`: https://github.com/sigstore/policy-controller/blob/ba6cdef1d82974440ea2eb23029fe6150bceb265/pkg/webhook/validator_result.go#L18-L36

I think we could add a `ResourceSpec interface{}` (with the `.spec` from the resource) and `Config map[string]v1.ConfigFile` (the string key for Config is to support [multi-arch images](https://github.com/google/go-containerregistry/blob/781782aa2757f8eb6d3b7b7a32b25a799b64bc60/pkg/v1/platform.go#L23-L31)).

This would let us access this context as part of the top-level `Policy` block here:
https://github.com/sigstore/policy-controller/blob/ba6cdef1d82974440ea2eb23029fe6150bceb265/pkg/apis/policy/v1beta1/clusterimagepolicy_types.go#L60-L64

### Other Considerations (incl. alternatives)

Including the resource spec as part of the policy result felt like a natural extension of the relatively new `Match` capabilities, but allowing users to BYO free form validation over the resource specification: https://github.com/sigstore/policy-controller/blob/ba6cdef1d82974440ea2eb23029fe6150bceb265/pkg/apis/policy/v1beta1/clusterimagepolicy_types.go#L71-L73

We could make providing this information opt-in via fields (e.g. `includeConfig: true`, `includeSpec: true`), I don't love the names, so if you have better names, feel free to offer up alternatives.  I'd also be fine with simply always including this information.

One alternative for the config file would be to have users project it as an attestation, but this felt awkward and frankly redundant since the config file is already associated with the container and part of the signed merkle tree.

Another alternative for the config file was to introduce a special case `predicateType` that accessed the image's embedded config  instead of requiring an explicit attestation, but this feels a bit to magical IMO.

**Comment by hectorj2f** [comment]
@vaikas Should we close this issue now ?

**Comment by mattmoor** [comment]
I think we still need the workload spec piece, but that should be much simpler 🤞

**Comment by hectorj2f** [comment]
Closing this issue! @vaikas added the last master piece here https://github.com/sigstore/policy-controller/pull/406
