### ISSUE TITLE
Verify "make docs" has been run

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#394]
**Description**

We should add a check to our GitHub actions that checks for things like has `./hack/update-codegen.sh` been run to also check to make sure that `make docs` has been run.

**Comment by vaikas** [comment]
Should be fairly similar to this action:
https://github.com/sigstore/policy-controller/blob/main/.github/workflows/verify-codegen.yaml

**Comment by hectorj2f** [comment]
Yeah, we need that ⛑️

**Comment by vaikas** [comment]
closed with #395 
Thanks @hectorj2f
