### ISSUE TITLE
CIP authority - AWS KMS alias is not accepted

### ISSUE THREAD

**Issue by oscarbetancurj** [sigstore/policy-controller#401]
**Description**

When I create a clusterImagePolicy using as authority AWS KMS, alias format is not working. This was working in previous versions.

Error message when I use AWS KMS alias: "Error from server (BadRequest): error when creating "cip.yaml": admission webhook "validating.clusterimagepolicy.sigstore.dev" denied the request: validation failed: invalid value: awskms:///alias/cosign-test-key: spec.authorities[0].key.kms"

YAML

apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: custom-key
spec:
  images:
  - glob: "**"
  authorities:
  - name: kms-key
     key:
       kms: awskms:///alias/cosign-test-key 

Changing the alias to the ARN works fine.

**Version**

0.3.8

**Comment by hectorj2f** [comment]
@oscarbetancurj Yes, this is a known limitation, as you can see here: https://github.com/sigstore/policy-controller/blob/main/pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go#L318. We should support the same valid kms settings supported by `cosign` here.

**Comment by oscarbetancurj** [comment]
@hectorj2f So, from now on, we need to use ARN format for policy controller and soon in cosign too?

**Comment by oscarbetancurj** [comment]
I used before the alias in previous versions of policy controller. So maybe was a change in the latest versions.

**Comment by hectorj2f** [comment]
Generally we rely on sigstore code to handle kms references, so I believe the problem comes from the validations.

**Comment by hectorj2f** [comment]
Closing this as solved in #524 where we changed our validation of aws kms refs.
