### ISSUE TITLE
policy-tester: check for unknown fields

### ISSUE THREAD

**Issue by mattmoor** [sigstore/policy-controller#451]
**Description**

It'd be nice if policy-tester checks for unknown fields when parsing the resource.  The webhook does this validation when the CIP is applied, but this validation is missing from the `policy-tester` deserialization logic.

I was playing with `source:` and had too much indentation and it was failing when it should have been passing :(

**Version**

Latest release

**Comment by hectorj2f** [comment]
@mattmoor check this PR https://github.com/sigstore/policy-controller/pull/453. Let me know if it is enough.
