### ISSUE TITLE
Revisit the earlier decision to not support `Status` field in CIP

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#456]
**Description**

While ago when we were designing the CIP shape, it was deemed that we do not want to add a Status field. IIRC some of the pushback may have been that other 'policy' type resources in k8s do not support it. However, there are some cases where it would be useful to surface some errors in the CIPs via Status field when the CIPs are being reconciled into the ConfigMap. So, just opening up this issue to start the discussion about it.

**Comment by hectorj2f** [comment]
With all the new references we have to other objects, it'd be also interesting to store error messages as status conditions.

**Comment by hectorj2f** [comment]
By the way we should use `status.conditions`, so we should come up with a list of status.

**Comment by hectorj2f** [comment]
I have couple of ideas for the status of policies:
* We should reflect the mode of the policy so it is easier to identify their current enforce mode: Warn, DenyAll
* The status needs to reflect the state of the policy especially after a reconciliation. For instance, if we are pulling KMS keys, or policies from configmap or URL that don't exist. The policy needs to reflect these states: Active, Error, Warn...
* It should also give a descriptive error message about the potential issues found from a missing ConfigMap, a wrong policy.url, etc...


I also had a look at gatekeeper policy status but I don't feel we should keep track of violations and affected pods.

**Comment by vaikas** [comment]
I don't agree about reflecting the fields from Spec => Status (warn, deny). Reasoning is that it's in the Spec and if Status says ready, then it provides no additional value.
I'm not sure what the 'Active', 'Error', 'Warn' states are?

**Comment by hectorj2f** [comment]
> I don't agree about reflecting the fields from Spec => Status (warn, deny). Reasoning is that it's in the Spec and if Status says ready, then it provides no additional value.

Yes, I had second thoughts on that, I also agree.

> I'm not sure what the 'Active', 'Error', 'Warn' states are?

Active == Ready, but I don't have strong feelings about it.
