### ISSUE TITLE
Implement policy.URL

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#458]
**Description**

I had originally lumped this into #454 but since this one is a bit different as far as how to be able to detect changes, broke into it's own issue.

We have a policy.URL field defined here:
https://github.com/sigstore/policy-controller/blob/main/pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go#L224

But it's not implemented and if you try to specify it the CIP is not validated and fails.

We should implement it.
Overall should be fairly straightforward, but the one thing that's worthy of a discussion is how to handle the fact that the contents of the URL can change. Because the CIP is reconciled when there are changes to it, if the contents of the URL change, we will not be privy to it. We have a similar issue with KMS keys, but they tend to be more slow changing than say a URL (esp. when doing dev work), so using the CRD resync policy might not be the best way to handle these. We could also fetch the URL during the validation, which then introduces potentially more latency, but also failure paths. So we should think about the best way to implement this.

**Comment by hectorj2f** [comment]
@vaikas We should document that any change to the kms key or url content won't be detected. We might want to find a common solution for both approaches. I feel we should add it as part of the logic added in the resync period.

**Comment by vaikas** [comment]
I guess the one thing is to think about how frequently things change indeed. What I was originally worried about was the dev experience. I think one way to address the 'dev' case is that you can actually change the CIP (add a placeholder label) and force a reconcile, but it's a bit hacky. With KMS I reckon the keys are changing much less frequently so doing dev seems fine and the bigger issue is key rotation, which I think the reconcile resync handles just fine.

One thought is that using cache control headers would be probably the most natural way, but we'd still have to figure out how to honor them to get a reconcile to happen after the cache expires.

**Comment by hectorj2f** [comment]
Honestly, I feel we shouldn't overcomplicate it. I see two options more k8s native in my opinion:

* Add annotations or labels to re-sync these items more often than others.
* For the url use case, I'd propose adding a `checksum` field so any change to the url needs an update of that checksum. It isn't the best experience but it is also secure.

wdyt ?

**Comment by vaikas** [comment]
I agree about not overcomplicating but also want to think about the user experience is something that makes sense during operation and accounting for reliable updates when things change.
As far as k8s native, I just think making sure we keep in mind the way more well established HTTP semantics should be kept in mind so there are no surprises :) 
HTTP has both the etag as well as cache-headers already built in and they live outside the scope of k8s already why things are harder. So, even if we use annotations/labels to reconcile (or whatever mechanism is used to reconcile), depending on for example how the HTTP headers are set, one wouldn't necessarily get the modified code since intermediates could cache the URL and that would be a bit surprising especially since without `status` in place, there's no way for the user (without looking at the configmap) to see what the actual fetched policy is.
As far as checksum, I wonder if we could utilize etag for it?

**Comment by vaikas** [comment]
For example, if I were to just drop some policy into GCS, I could get bit by the default caching policy because even if we then reconciled the object, one would get the old policy:
https://cloud.google.com/storage/docs/caching

**Comment by hectorj2f** [comment]
Yes, etag is a hash of the content :) which solves our problem here. That is what I meant by using checksum here.
I think we can use etag here, in fact by reading gcs docs... it sounds good to cover our back:

```
If an ETag is provided and matches the current resource ETag, the request succeeds; otherwise, it fails with a FAILED_PRECONDITION error and an HTTP status code 400. If an ETag is not provided, the request proceeds without checking the currently stored ETag value.
```

**Comment by vaikas** [comment]
Yeah, it's usually implemented as a hash, but it doesn't really have to be and iirc it's not even specified how it's computed but for detecting if things have changed it should suffice.

**Comment by hectorj2f** [comment]
@vaikas and myself discussed all the options and decided to add a new field `shasum` to enforce our security when pulling the policy from the url.
