### ISSUE TITLE
Policy controller doesn't work due to invalid clusterRole permissions to apiextensions.k8s.io for policy-controller-policy-webhook

### ISSUE THREAD

**Issue by kilowhiskey** [sigstore/policy-controller#46]
{"level":"error","ts":"2022-06-20T09:19:39.406Z","logger":"clusterimagepolicy.ConversionWebhook","caller":"controller/controller.go:566","msg":"Reconcile error","knative.dev/traceid":"ae4cbf50-6b16-4cf5-a247-faa6cacb0f94","knative.dev/key":"clusterimagepolicies.policy.sigstore.dev","duration":0.098656086,"error":"failed to update webhook: customresourcedefinitions.apiextensions.k8s.io \"clusterimagepolicies.policy.sigstore.dev\" is forbidden: User \"system:serviceaccount:cosign-system:**policy-controller-policy-webhook**\" cannot update resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:491"}

Cluster role binding in 201-clusterrolebinding.yaml gives rbac permissions to **policy-controller-webhook** service account
however the service account created and used is called **policy-controller-policy-webhook** and webhook is not registered.

**Comment by kilowhiskey** [comment]
I think the description is incorrect anyway there is something not ok with the ClusterRoleBinding or Definition

**Comment by hectorj2f** [comment]
The last error could be ignored, as the reconciler retries on error. It is a common error when retrying to update a resource, the reconciler will fail and retry again.

I added an update permission to an existing PR.

**Comment by hectorj2f** [comment]
@kilowhiskey Closing this issue as fixed by https://github.com/sigstore/helm-charts/pull/224/commits/3d5f7160a7d635d9d9e9fe5cfc0fe3a00c383e26. Feel free to re-open it.
