### ISSUE TITLE
How can I validation image in a https harbor 

### ISSUE THREAD

**Issue by maoyangLiu** [sigstore/policy-controller#477]
**Question**
1. I met a question like this ,whtn I apply a deployment after installed  admission webhook "policy.sigstore.dev", An error occurred。It"s log " signature key validation failed for authority authority-0 for10.49.38.75:30003/library/tomcat@sha256:0758380e1e0c304cd3205fbca241930156975a8f62c4db1d8d7939976189e7ff: GET http://10.49.38.75:30003/v2/: unexpected status code 400 Bad Request"

2.the harbor address 10.49.38.75:30003, and iti is a https address,but why he send a http request, Is it because I lack the configuration？
3. If use the command cosign I can use cosign sign -- --allow-insecure-registry, so how should I configure in policy-controller.

Can someone help me? Thank you very much

**Comment by hectorj2f** [comment]
You should configure the container registry credentials as secrets, you can learn more from this link https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/. 

The policy-controller reuses the secrets configured in the spec of your specific resource:

```
  imagePullSecrets:
  - name: regcred
 ```

**Comment by hectorj2f** [comment]
@maoyangLiu can you confirm it works for you now?

**Comment by qicheng676** [comment]
> 

3. If use the command cosign I can use cosign sign -- --allow-insecure-registry, so how should I configure in policy-controller.

Has the third question been resolved？

**Comment by hectorj2f** [comment]
@qicheng676 Indeed we don't have a way to set `--allow-insecure-registry=true` in our API types. We enforce the usage of a secure connection against registries. Please, feel free to open a particular issue to discuss adding support for this flag in our API :).

**Comment by qicheng676** [comment]
> @qicheng676 Indeed we don't have a way to set `--allow-insecure-registry=true` in our API types. We enforce the usage of a secure connection against registries. Please, feel free to open a particular issue to discuss adding support for this flag in our API :).

Thanks. https://github.com/sigstore/policy-controller/issues/605 solved my problem
