### ISSUE TITLE
Add support for self signed certificates for registries

### ISSUE THREAD

**Issue by elfotografo007** [sigstore/policy-controller#52]
**Description**

We need to add support for handling container registries using self-signed certificates.

Moved from https://github.com/sigstore/cosign/issues/1826

**Comment by elfotografo007** [comment]
I am sorry for the confusion but it has not been resolved yet. We still need to add support for self-signed CAs.

**Comment by hectorj2f** [comment]
Yes, we closed the original one. There were not conversations or threads, so it looked like a safe issue migration.

**Comment by derwei** [comment]
Hi @hectorj2f @vaikas !!
any thoughts on the above PR?

**Comment by hectorj2f** [comment]
@derwei Are you referring to this effort https://github.com/sigstore/helm-charts/pull/453 ? Or do you refer to this feature in general ? There is not any progress regarding the later.

**Comment by derwei** [comment]
Yup! I was referring to https://github.com/sigstore/helm-charts/pull/453

**Comment by hectorj2f** [comment]
@derwei @elfotografo007 It looks good to me.
