### ISSUE TITLE
'Cut Release' gh action failed to upload the provenance data

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/policy-controller#638]
**Description**

Provenance step is failing to upload the provenance data to the gh release. The reason is still unknown.

https://github.com/sigstore/policy-controller/actions/runs/4286111265

**Version**

v0.7.0

**Comment by cpanato** [comment]
will check that

**Comment by hectorj2f** [comment]
Thanks @cpanato 🙌🏻
