### ISSUE TITLE
Decide on release cadence and process

### ISSUE THREAD

**Issue by vaikas** [sigstore/policy-controller#71]
We've talked about this before, but now that policy-controller is in it's own repo, we should define the release cadence and how we decide when to cut releases. We also need to cut a release, so let's use this to bootstrap the process. @cpanato probably has some ideas here :)

**Comment by hectorj2f** [comment]
I'd suggest a bi-weekly release cadence unless there are major bugs or vulnerabilities. Depending of the released features, we could decide bumping to new minor releases.

Which version are we considering using as our first release `v0.1.0` ?

**Comment by vaikas** [comment]
Because english is hard for me and I think bi-weekly means either twice a week or every two weeks, just to double-check, do you mean every 2 weeks?

That seems quite frequent in either case. For bugs/vulns I'd like to get those cut asap.

In Knative we cut every 6 weeks and some folks felt that was too frequent in order for them to keep up with the releases and be able to roll them out.

What was the last release of cosigned webhook? I took a quick look at cosign releases and I couldn't find one there.

**Comment by hectorj2f** [comment]
Yeah, i was not precise about that. I meant every 2 weeks under normal circumstances, i assumed if there is a bug, we release asap.

> In Knative we cut every 6 weeks and some folks felt that was too frequent in order for them to keep up with the releases and be able to roll them out.

I am okay with 6 weeks.

**Comment by hectorj2f** [comment]
> What was the last release of cosigned webhook?

We were following the same release cadence as cosign

**Comment by vaikas** [comment]
I'll try to create a new release now.

**Comment by vaikas** [comment]
@cpanato are these still the correct instructions to use?
https://github.com/sigstore/policy-controller/tree/main/release

I couldn't figure out some of the values and looks like not everybody can run releases, so just checking :)

**Comment by hectorj2f** [comment]
> I couldn't figure out some of the values and looks like not everybody can run releases, so just checking :

That is correct, we could not run releases.

**Comment by cpanato** [comment]
sorry missed this notification.

I will update the documentation, we have an action similar we have for the other repos to trigger the cloudbuild. 

For the cadence, I can draft a PR for a suggestion, but i would say what about once a month as default, but we if need any patches or urgent release we do adhoc?
