### ISSUE TITLE
How can I configure multiple self-signed certificates?

### ISSUE THREAD

**Issue by jacckyyy** [sigstore/policy-controller#832]
**Question**

I have used the following method to configure a self-signed certificate in the policy-controller. However, in my environment, I need to use more than one private registry. Is there any way to configure multiple self-signed certificates? thanks a lot.

```shell
kubectl -n consign-system create cm ca-bundle-config \
   --from-file=cabuldle/crt="ca-bundle.crt"
```
```shell
helm install --n cosign-system \
    --set webhook.registryCaBundle.name=ca-bundle-config \
    --set webhook.registryCaBundle.key=ca-bundle.crt \
    policy-controller sigstore/policy-controller
```

**Comment by hectorj2f** [comment]
@jacckyyy Sorry for this late reply. At this moment, our helm-chart only assumes a single signed certificate is used. You'd need to add support for multiple self-signed certs.

**Comment by jacckyyy** [comment]
I got it, I have tried to add multiple self-signed certificates chain into a .crt file, and then configure to webhook. It's work with multiple self-signed certificates now, many thanks.
